names = {
    'diff': 'Diffuse',
    'rough': 'Rough',
    'metal': 'Metal',
    'nor_gl': 'nor_gl',
    'nor_dx': 'nor_dx',
    'disp': 'Displacement',
    'ao': 'AO',
    'bump': 'Bump',
    'alpha': 'Alpha',
    'emission': 'Emission',
    'mask': 'Mask',
}

aliases = {
    'diffuse': 'diff',
    'dif': 'diff',
    'alb': 'diff',
    'albedo': 'diff',
    'col': 'diff',
    'color': 'diff',
    'basecolor': 'diff',
    'roughness': 'rough',
    'metallic': 'metal',
    'nor': 'nor_gl',
    'norm': 'nor_gl',
    'normal': 'nor_gl',
    'height': 'disp',
    'displacement': 'disp',
    'transparent': 'alpha',
}
